---
# roles/aws.provision/tasks/00_key.yml

#---------------------------------------------------
# Key
#---------------------------------------------------
- name: Include vars of aws-keys.yaml
  include_vars:
    file: /home/rpavlice/aws-keys.yml

- name: Check key exists
  stat:
    path: "{{ local_keypair }}"
  register: stat_result

- name: Remove remote key
  ec2_key: name="{{ remote_user_sshkey }}" region="{{ aws_region }}" state=absent
  when: stat_result.stat.exists == False
  ignore_errors: yes

- name: Create new key
  ec2_key: name="{{ remote_user_sshkey }}" region="{{ aws_region }}" state=present
  register: ec2_key
  when: stat_result.stat.exists == False

- name: Create hidden directory
  file: path="{{ local_workspace }}" state=directory
  when: stat_result.stat.exists == False

- name: Copy key file
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "{{ local_keypair }}"
    mode: 0400
  when: stat_result.stat.exists == False

- name: Set key permissions
  file:
   path: "{{ local_keypair }}"
   state: touch
   mode: 0400
  when: stat_result.stat.exists == False

- name: Set ec2 key
  ec2_key:
    name: "{{ remote_user_sshkey }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_material: "{{ item }}"
    force: false
    state: present
  with_file: "{{ local_keypair }}"
  register: ec2_key
  when: stat_result.stat.exists == True
  ignore_errors: yes
