# These are tasks which have to wait until last when deleting an environment
#
# Remove the security group, which needs all reliant structures removed first:
- name: delete ec2 group
  ec2_group:
    name: "{{ seg_vpc }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: "{{newstate }}"
  register: sec_grp_results
  when: newstate == "absent"
