---
#############################################################
# Provision AWS infrastructure
#############################################################
- name: Create Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
   - aws.infra
   - ocp4

